/**
 * @file
 */
class Util {
    constructor() {

    }
}

const OPTIONS = {hour12: false};

Util.formatDate = function (seconds) {
    const date = new Date(seconds * 1000);
    return date.toLocaleString('zh-Hans-CN', OPTIONS);
};

Date.prototype.format = function () {
    var y = this.getFullYear();
    var m = bit_format(this.getMonth() + 1);
    var d = bit_format(this.getDate());
    var h = bit_format(this.getHours());
    var mins = bit_format(this.getMinutes());
    var secs = bit_format(this.getSeconds());
    return y + '-' + m + '-' + d + " " + h + ":" + mins + ':' + secs;
}

function bit_format(origin) {
    return (origin > 9 ? origin : '0' + origin);
}


Util.chinaCityMap = {
    'anhui': '安徽',
    'aomen': '澳门',
    'beijing': '北京',
    'chongqing': '重庆',
    'fujian': '福建',
    'gansu': '甘肃',
    'guangdong': '广东',
    'guangxi': '广西',
    'guizou': '贵州',
    'hainan': '海南',
    'hebei': '河北',
    'heilongjiang': '黑龙江',
    'henan': '河南',
    'hubei': '湖北',
    'hunan': '湖南',
    'jiangsu': '江苏',
    'jiangxi': '江西',
    'jilin': '吉林',
    'liaoning': '辽宁',
    'neimenggu': '内蒙古',
    'ningxia': '宁夏',
    'qinghai': '青海',
    'shaanxi': '陕西',
    'shandong': '山东',
    'shanghai': '上海',
    'shanxi': '山西',
    'sichuan': '四川',
    'taiwan': '台湾',
    'tianjin': '天津',
    'xianggang': '香港',
    'xinjiang': '新疆',
    'xizang': '西藏',
    'yunnan': '云南',
    'zhejiang': '浙江'
}
Util.worldNameMap = {
    AE: 'United Arab Emirates',
    AF: 'Afghanistan',
    AL: 'Albania',
    AM: 'Armenia',
    AO: 'Angola',
    AR: 'Argentina',
    AT: 'Austria',
    AU: 'Australia',
    AZ: 'Azerbaijan',
    BA: 'Bosnia and Herzegovina',
    BD: 'Bangladesh',
    BE: 'Belgium',
    BF: 'Burkina Faso',
    BG: 'Bulgaria',
    BI: 'Burundi',
    BJ: 'Benin',
    BN: 'Brunei Darussalam',
    BO: 'Bolivia',
    BR: 'Brazil',
    BT: 'Bhutan',
    BW: 'Botswana',
    BY: 'Belarus',
    BZ: 'Belize',
    CA: 'Canada',
    CD: 'Republic of the Congo',
    CF: 'Central African Republic',
    CG: 'Democratic Republic of the Congo',
    CH: 'Switzerland',
    CI: 'Ivory Coast',
    CL: 'Chile',
    CM: 'Cameroon',
    CN: 'China',
    CO: 'Colombia',
    CR: 'Costa Rica',
    CU: 'Cuba',
    CY: 'Cyprus',
    CZ: 'Czech Republic',
    DE: 'Germany',
    DJ: 'Djibouti',
    DK: 'Denmark',
    DO: 'Dominican Republic',
    DZ: 'Algeria',
    EC: 'Ecuador',
    EE: 'Estonia',
    EG: 'Egypt',
    EH: 'Western Sahara',
    ER: 'Eritrea',
    ES: 'Spain',
    ET: 'Ethiopia',
    FI: 'Finland',
    FJ: 'Fiji',
    FK: 'Falkland Islands (Malvinas)',
    FR: 'France',
    GA: 'Gabon',
    GB: 'United Kingdom',
    GE: 'Georgia',
    GF: 'French Guiana',
    GH: 'Ghana',
    GL: 'Greenland',
    GM: 'Gambia',
    GN: 'Guinea',
    GQ: 'Equatorial Guinea',
    GR: 'Greece',
    GT: 'Guatemala',
    GW: 'Guinea-Bissau',
    GY: 'Guyana',
    HN: 'Honduras',
    HR: 'Croatia',
    HT: 'Haiti',
    HU: 'Hungary',
    ID: 'Indonesia',
    IE: 'Ireland',
    IL: 'Israel',
    IN: 'India',
    IQ: 'Iraq',
    IR: 'Iran',
    IS: 'Iceland',
    IT: 'Italy',
    JM: 'Jamaica',
    JO: 'Jordan',
    JP: 'Japan',
    KE: 'Kenya',
    KG: 'Kyrgyzstan',
    KH: 'Cambodia',
    KP: 'North Korea',
    KR: 'South Korea',
    KW: 'Kuwait',
    KZ: 'Kazakhstan',
    LA: 'Laos',
    LB: 'Lebanon',
    LK: 'Sri Lanka',
    LR: 'Liberia',
    LS: 'Lesotho',
    LT: 'Lithuania',
    LU: 'Luxembourg',
    LV: 'Latvia',
    LY: 'Libya',
    MA: 'Morocco',
    MD: 'Republic of Moldova',
    MG: 'Madagascar',
    MK: 'The Former Yugoslav Republic of Macedonia',
    ML: 'Mali',
    MM: 'Myanmar',
    MN: 'Mongolia',
    MR: 'Mauritania',
    MW: 'Malawi',
    MX: 'Mexico',
    MY: 'Malaysia',
    MZ: 'Mozambique',
    NA: 'Namibia',
    NC: 'New Caledonia',
    NE: 'Niger',
    NG: 'Nigeria',
    NI: 'Nicaragua',
    NL: 'Netherlands',
    NO: 'Norway',
    NP: 'Nepal',
    NZ: 'New Zealand',
    OM: 'Oman',
    PA: 'Panama',
    PE: 'Peru',
    PG: 'Papua New Guinea',
    PH: 'Philippines',
    PK: 'Pakistan',
    PL: 'Poland',
    PR: 'Puerto Rico',
    PS: 'Occupied Palestinian Territory',
    PT: 'Portugal',
    PY: 'Paraguay',
    QA: 'Qatar',
    RO: 'Romania',
    RS: 'Serbia',
    RU: 'Russia',
    RW: 'Rwanda',
    SA: 'Saudi Arabia',
    SB: 'Solomon Islands',
    SD: 'South Sudan',
    SE: 'Sweden',
    SJ: 'Svalbard and Jan Mayen',
    SK: 'Slovakia',
    SL: 'Sierra Leone',
    SN: 'Senegal',
    SO: 'Somalia',
    SR: 'Suriname',
    SV: 'El Salvador',
    SY: 'Syria',
    SZ: 'Swaziland',
    TD: 'Chad',
    TG: 'Togo',
    TH: 'Thailand',
    TJ: 'Tajikistan',
    TL: 'Timor-Leste',
    TM: 'Turkmenistan',
    TN: 'Tunisia',
    TR: 'Turkey',
    TW: 'Province of China Taiwan',
    TZ: 'United Republic of Tanzania',
    UA: 'Ukraine',
    UG: 'Uganda',
    US: 'United States of America',
    UY: 'Uruguay',
    UZ: 'Uzbekistan',
    VE: 'Venezuela',
    VN: 'Vietnam',
    VU: 'Vanuatu',
    YE: 'Yemen',
    ZA: 'South Africa',
    ZM: 'Zambia',
    ZW: 'Zimbabwe'
}

export default Util;
